function areaRatio = areaMachFunction(gamma, M)
% A/A* as function of Mach number (A*: sonic area for isentropic flow)
areaRatio = ...
    ((gamma+1)/2)^(-(gamma+1)/2/(gamma-1)) * ...
    (1 + (gamma-1)/2 * M.^2 ).^ ...
    ((gamma+1)/2/(gamma-1)) ...
    ./ M;