figure(11); clf;
tL = agtools.plotBubble_light( ...
    fullState, ...
    solution_reference, ...
    metadata_reference);
agtools.plotBubble_light( ...
    fullState_noshuttle, ...
    solution_noshuttle, ...
    metadata_noshuttle, ...
    tL, [48, 186, 69]/255);
nexttile(1)