%% Double contour-plot
figure(6); clf
[C2, h2] = agtools.plotFiringChamber_xt_nofill( ...
    fullState_noshuttle, metadata_noshuttle, caseKeyContext, ...
    [48, 186, 69]/255);
clabel(C2,h2,[6.5, 4, 2.0, 1.5], 'Color', [92, 219, 42]/255, ...
    'FontSize', 14, 'Interpreter', 'tex')
hold on
[C1, h1] = agtools.plotFiringChamber_xt_nofill( ...
    fullState, metadata_reference, caseKeyContext, ...
    [0, 0, 0]);
clabel(C1,h1,[6.5, 4.5, 4, 2.5, 2.0, 1.5], 'labelspacing', 160, ...
    'FontSize', 14, 'Interpreter', 'tex');
ylim([0, 50])

legend([h1, h2], {'Coupled model', 'Simplified port treatment'}, ...
       'location', 'southwest', ...
       'Interpreter', 'tex', ...
       'FontSize', 13)

set(gca,'FontSize', 14, 'TickLabelInterpreter', 'tex');
xlabel("{\it{x}} (m)", "Interpreter", "tex", 'FontSize', 15)
ylabel("{\it{t}} (ms)", "Interpreter", "tex", 'FontSize', 15)